openkruise/openkruise.io

- i18n/zh/docusaurus-plugin-content-docs/current/cli-tool/kubectl-plugin.md
- package.json
- sidebars.js
- yarn.lock
Add docs for kubectl-kruise and upgrade docusaurus version
> Add docs for kubectl-kruise and upgrade docusaurus version

- docs/user-manuals/resourcedistribution.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/resourcedistribution.md
- sidebars.js
Signed-off-by: veophi <vec.g.sun@gmail.com>
Add ResourceDistribution Doc.
> Add ResourceDistribution Doc

- docs/user-manuals/cloneset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
Signed-off-by: veophi <vec.g.sun@gmail.com>
Add ScaleStrategy.MaxUnavailable docs for CloneSet
> Add ScaleStrategy.MaxUnavailable docs for CloneSet

- docs/user-manuals/sidecarset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/sidecarset.md
- versioned_docs/version-v0.10/user-manuals/sidecarset.md
> fix sidecarset sample

- docs/core-concepts/inplace-update.md
- docs/user-manuals/containerlaunchpriority.md
- docs/user-manuals/resourcedistribution.md
- i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/inplace-update.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/containerlaunchpriority.md
Update docs for features in v1.0
> Update docs for features in v1.0

- blog/2021-05-20-release-0.9.0.md
- blog/2021-09-06-release-0.10.0.md
- i18n/zh/docusaurus-plugin-content-blog/2021-05-20-release-0.9.0.md
- i18n/zh/docusaurus-plugin-content-blog/2021-09-06-release-0.10.0.md
- src/css/custom.css
Add blogs for releases 0.9.0 and 0.10.0
> Add blogs for releases 0.9.0 and 0.10.0

- blog/2021-12-13-release-1.0.md
- i18n/zh/docusaurus-plugin-content-blog/2021-12-13-release-1.0.md
> Improve blog v1.0

- blog/2021-12-13-release-1.0.md
- docs/introduction.md
- i18n/zh/code.json
- src/components/HomepageFeatures.js
- src/pages/index.js
- versioned_docs/version-v0.10/introduction.md
- versioned_docs/version-v1.0/introduction.md
> Fix typo and zero space

- docs/cli-tool/kubectl-plugin.md
- i18n/zh/docusaurus-plugin-content-docs/current/cli-tool/kubectl-plugin.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/cli-tool/kubectl-plugin.md
- versioned_docs/version-v1.0/cli-tool/kubectl-plugin.md
> add krew install kruise docs

- .github/workflows/documentation.yaml
> Enable jsdelivr CDN

- docusaurus.config.js
> Show all blogs

- docs/developer-manuals/go-client.md
- i18n/zh/docusaurus-plugin-content-docs/current/developer-manuals/go-client.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/developer-manuals/go-client.md
- versioned_docs/version-v1.0/developer-manuals/go-client.md
> Fix kruise-api version

- docs/installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/installation.md
- versioned_docs/version-v1.0/installation.md
> Update version 1.0.1

- docs/best-practices/gitops-with-kruise.md
- i18n/zh/docusaurus-plugin-content-docs/current/best-practices/gitops-with-kruise.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/gitops-with-kruise.md
- versioned_docs/version-v1.0/best-practices/gitops-with-kruise.md
> modify best practices gitops

- README.md
> test update README

- docs/installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/installation.md
- versioned_docs/version-v1.0/installation.md
Add tips for installation on EKS. Reference to https://github.com/openkruise/kruise/issues/908
> Add tips for installation on EKS

- sidebars.js
- versioned_sidebars/version-v1.0-sidebars.json
Signed-off-by: veophi <vec.g.sun@gmail.com>
> Adjust the sidebar of best practices

- docusaurus.config.js
- src/css/custom.css
> Fix custom css for blog title

- docs/cli-tool/kubectl-plugin.md
- i18n/zh/docusaurus-plugin-content-docs/current/cli-tool/kubectl-plugin.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/cli-tool/kubectl-plugin.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.1/cli-tool/kubectl-plugin.md
- versioned_docs/version-v1.0/cli-tool/kubectl-plugin.md
- versioned_docs/version-v1.1/cli-tool/kubectl-plugin.md
Signed-off-by: hantmac <hantmac@outlook.com>
update kruise tool docs
> update kruise tool docs

- .github/workflows/documentation.yaml
> Remove cdn acceleration

- .github/workflows/documentation.yaml
- src/css/custom.css
> Fix workflow action yaml

- docs/user-manuals/advanceddaemonset.md
- docs/user-manuals/advancedstatefulset.md
- docs/user-manuals/cloneset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advanceddaemonset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advancedstatefulset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
Signed-off-by: mingzhou.swx <mingzhou.swx@alibaba-inc.com>
- Add docs for PRs:
- https://github.com/openkruise/kruise/pull/954
-  https://github.com/openkruise/kruise/pull/963
- https://github.com/openkruise/kruise/pull/979
- https://github.com/openkruise/kruise/pull/980
> update cloneset statefulset daemonset docs for kruise 1.2.0

- docs/introduction.md
- versioned_docs/version-v0.10/introduction.md
- versioned_docs/version-v1.0/introduction.md
- versioned_docs/version-v1.1/introduction.md
- versioned_docs/version-v1.2/introduction.md
> Fix typo of introduction

- docs/installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-v0.10/installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.1/installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.2/installation.md
- versioned_docs/version-v0.10/installation.md
- versioned_docs/version-v1.0/installation.md
- versioned_docs/version-v1.1/installation.md
- versioned_docs/version-v1.2/installation.md
Update doc to latest version 1.2.0
> Update the installation doc to the latest version `1.2.0`

- docs/user-manuals/cloneset.md
The URL is broken, Instead of https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost.
> Update 'controller.kubernetes.io/pod-deletion-cost' url

- docs/user-manuals/broadcastjob.md
From the PR https://github.com/openkruise/kruise/pull/126, we can see the BroadcastJob field `BackoffLimit` was replaced by `RestartLimit`, so this PR is to make it consistent.
Also added default mark on `CompletionPolicy.Always` and `FailurePolicy.FailFast`.
But the doc in `i18n` and `versioned_docs` dir was not updated accordingly, as there may be some auto-translation or doc-version controll script to do the job. If need manually do the job, I will open another PR.
> Fix doc of BroadcastJob from `BackoffLimit` to `RestartLimit`

- docs/user-manuals/podprobemarker.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/podprobemarker.md
- sidebars.js
> pod probe marker docs

- docs/user-manuals/advancedcronjob.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advancedcronjob.md
> Add TimeZone into acj doc

- docs/user-manuals/cloneset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
add scaling with PreparingDelete in CloneSet doc
> Add scaling with PreparingDelete in CloneSet doc

- docs/user-manuals/advanceddaemonset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advanceddaemonset.md
Add PreDownloadImageForDaemonSetUpdate featureGate into doc
> Add PreDownloadImageForDaemonSetUpdate featureGate into doc

- docs/user-manuals/sidecarset.md
- docs/user-manuals/workloadspread.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/workloadspread.md
Signed-off-by: mingzhou.swx <mingzhou.swx@alibaba-inc.com>
Add SidecarSet and WorkloadSpread docs for 1.3.0
> Add SidecarSet and WorkloadSpread docs for 1.3.0

- docs/user-manuals/sidecarset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/sidecarset.md
- versioned_docs/version-v1.3/user-manuals/sidecarset.md
docs: fix the wrong code sample #86 
fix the wrong code sample about white list config map
Signed-off-by: Jason Tsai <caihaiboy@gmail.com>
> Sidecarset doc fix

- docs/introduction.md
- docs/user-manuals/advanceddaemonset.md
- docs/user-manuals/advancedstatefulset.md
- docs/user-manuals/cloneset.md
- versioned_docs/version-v0.10/introduction.md
- versioned_docs/version-v0.10/user-manuals/advanceddaemonset.md
- versioned_docs/version-v0.10/user-manuals/advancedstatefulset.md
- versioned_docs/version-v0.10/user-manuals/cloneset.md
- versioned_docs/version-v1.0/introduction.md
- versioned_docs/version-v1.0/user-manuals/advanceddaemonset.md
- versioned_docs/version-v1.0/user-manuals/advancedstatefulset.md
- versioned_docs/version-v1.0/user-manuals/cloneset.md
- versioned_docs/version-v1.1/introduction.md
- versioned_docs/version-v1.1/user-manuals/advanceddaemonset.md
- versioned_docs/version-v1.1/user-manuals/advancedstatefulset.md
- versioned_docs/version-v1.1/user-manuals/cloneset.md
- versioned_docs/version-v1.2/introduction.md
- versioned_docs/version-v1.2/user-manuals/advanceddaemonset.md
- versioned_docs/version-v1.2/user-manuals/advancedstatefulset.md
- versioned_docs/version-v1.2/user-manuals/cloneset.md
- versioned_docs/version-v1.3/introduction.md
- versioned_docs/version-v1.3/user-manuals/advanceddaemonset.md
- versioned_docs/version-v1.3/user-manuals/advancedstatefulset.md
- versioned_docs/version-v1.3/user-manuals/cloneset.md
modify kruise docs to target large-scale applications
> modify kruise to target large-scale applications

- OWNERS
> add zmberg as owner

- docs/user-manuals/cloneset.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/user-manuals/cloneset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/cloneset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/cloneset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/cloneset.md
- versioned_docs/version-v1.0/user-manuals/cloneset.md
- versioned_docs/version-v1.1/user-manuals/cloneset.md
- versioned_docs/version-v1.2/user-manuals/cloneset.md
- versioned_docs/version-v1.3/user-manuals/cloneset.md
Signed-off-by: fengshunli <1171313930@qq.com>
> fix multiple Scale features in cloneset.md

- docs/best-practices/ci-pipeline-image-predownload.md
Signed-off-by: lijianfeng [lijianfeng@cmss.chinamobile.com](mailto:lijianfeng@cmss.chinamobile.com)
fix Indentation problem of tekton pipeline yaml file in docs/best-practices/ci-pipeline-image-predownload.md
> fix Indentation problem of tekton pipeline yaml file 

- README.md
- i18n/zh/docusaurus-plugin-content-docs/current.json
- i18n/zh/docusaurus-plugin-content-docs/version-v0.10.json
- i18n/zh/docusaurus-plugin-content-docs/version-v1.1.json
- i18n/zh/docusaurus-plugin-content-docs/version-v1.2.json
- i18n/zh/docusaurus-plugin-content-docs/version-v1.3.json
- i18n/zh/docusaurus-plugin-content-docs/version-v1.4.json
fix https://github.com/openkruise/openkruise.io/issues/104
> correct labels for version dropdown

- i18n/zh/code.json
- src/pages/index.js
change 'sandbox project' to 'incubating project' on index page
> change 'sandbox project' to 'incubating project' on index page

- docs/user-manuals/broadcastjob.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/broadcastjob.md
- i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/broadcastjob.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.0/user-manuals/broadcastjob.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/broadcastjob.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/broadcastjob.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/broadcastjob.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/broadcastjob.md
- versioned_docs/version-v0.10/user-manuals/broadcastjob.md
- versioned_docs/version-v1.0/user-manuals/broadcastjob.md
- versioned_docs/version-v1.1/user-manuals/broadcastjob.md
- versioned_docs/version-v1.2/user-manuals/broadcastjob.md
- versioned_docs/version-v1.3/user-manuals/broadcastjob.md
- versioned_docs/version-v1.4/user-manuals/broadcastjob.md
> [FIX] remove BackoffLimit

- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/podprobemarker.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/podprobemarker.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/podprobemarker.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/podprobemarker.md
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels。
> [FIX] link click error

- .github/workflows/documentation.yaml
- src/css/custom.css
fix https://github.com/openkruise/openkruise.io/issues/108
> increase table font size

- i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advancedstatefulset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/advancedstatefulset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/advancedstatefulset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/advancedstatefulset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/advancedstatefulset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/advancedstatefulset.md
是否以及 <u>_合适_</u> 删除它所创建的PVC  
->  是否以及 <u>_何时_</u>  删除它所创建的PVC
> fix Chinese description of Advanced StatefulSet PVC retention

- docs/installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.6/installation.md
- versioned_docs/version-v1.6/installation.md
change kruise installation doc tag to 1.6.3
> kruise 1.6.3

- rollouts/user-manuals/strategy-multi-batch-update.md
Hi, OpenKruise team,
I've just noticed an issue in the rollout documentation.
> fix the example format issue on rollout

- i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/network.md
- kruisegame/user-manuals/network.md
refer https://github.com/openkruise/kruise-game/pull/179
> Add OKG network plugin: TencentCloud-CLB

- docs/user-manuals/sidecarset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.6/user-manuals/sidecarset.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.7/user-manuals/sidecarset.md
- versioned_docs/version-v1.6/user-manuals/sidecarset.md
- versioned_docs/version-v1.7/user-manuals/sidecarset.md
fix issue https://github.com/openkruise/kruise/issues/1735
> fix sidecarset sourceContainerNameFrom docs

- i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/network.md
- kruisegame/user-manuals/network.md
refer [https://github.com/openkruise/kruise-game/pull/180](url)
> docs:add OKG network plugin: JdCloud-NLB 、JdCloud-EIP

- .github/workflows/documentation.yaml
- .github/workflows/pre_dict.json
- docs/installation.md
- docs/operator-manuals/availability.md
- docs/operator-manuals/troubleshooting.md
- i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/api-specifications.md
- i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/basic-usage.md
- i18n/zh/docusaurus-plugin-content-docs/current.json
- i18n/zh/docusaurus-plugin-content-docs/current/operator-manuals/availability.md
- i18n/zh/docusaurus-plugin-content-docs/current/operator-manuals/troubleshooting.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.7.json
- i18n/zh/docusaurus-plugin-content-docs/version-v1.7/operator-manuals/availability.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.7/operator-manuals/troubleshooting.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.8.json
- i18n/zh/docusaurus-plugin-content-docs/version-v1.8/operator-manuals/availability.md
- i18n/zh/docusaurus-plugin-content-docs/version-v1.8/operator-manuals/troubleshooting.md
- rollouts/user-manuals/api-specifications.md
- rollouts/user-manuals/basic-usage.md
- sidebars.js
- versioned_docs/version-v1.7/operator-manuals/availability.md
- versioned_docs/version-v1.7/operator-manuals/troubleshooting.md
- versioned_docs/version-v1.8/operator-manuals/availability.md
- versioned_docs/version-v1.8/operator-manuals/troubleshooting.md
- versioned_sidebars/version-v1.7-sidebars.json
- versioned_sidebars/version-v1.8-sidebars.json
1. add basic operation guide. fix https://github.com/openkruise/kruise/issues/1588
2. improve and translate the following patchs: 
https://github.com/openkruise/openkruise.io/pull/249
https://github.com/openkruise/openkruise.io/pull/247
> Operator guide

- i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/network.md
- kruisegame/user-manuals/network.md
ref https://github.com/openkruise/kruise-game/pull/239
> update TencentCloud-CLB plugin

- blog/2025-02-19-elastic-components.md
- i18n/zh/docusaurus-plugin-content-blog/2025-02-19-elastic-components.md
https://github.com/openkruise/openkruise.io/pull/267#issuecomment-3130889101
> doc: remove incompatible field

- docs/faq.md
1. Workload Selection and Migration
2. Performance and Scaling
3. SidecarSet and Container Management
4. Security and RBAC
5. Monitoring and Observability
6. Troubleshooting and Debugging
7. Integration and Ecosystem
8. Best Practices and Recommendations
> Added comprehensive new questions in FAQ covering all major aspects

- i18n/zh/docusaurus-plugin-content-docs-rollouts/current/installation.md
- i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/api-specifications.md
- i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/basic-usage.md
- rollouts/installation.md
- rollouts/user-manuals/basic-usage.md
- rollouts/user-manuals/strategy-canary-update.md
Fix some typos in Rollout document.
> docs: correct spelling errors and typos in Rollout document
